### ISSUE TITLE
项目结构

### ISSUE THREAD

**Issue by Aitical** [whlzy/PR_EXP#1]
主目录下的trainer太多，而且trainer间存在大量冗余代码。陆哥可以把training pipeline 抽象出来，src/trainer中抽象出来一些不同的基础training pipeline，类似于pytorch lightning的Model，之后对于不同的网络、不同的pipeline只需要替换即可训练。

陆哥牛！yyds！

**Comment by whlzy** [comment]
好好好！刚哥，我改改，，刚哥也是yyds！😘
